/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package citylink;

import java.io.IOException;
import java.io.FileWriter;
import java.io.BufferedWriter;

/**
 *
 * @author burak
 */
public class AddNewRoute extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddNewRoute.class.getName());

    /**
     * Creates new form AddNewRoute
     */
    public AddNewRoute() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        addNewRouteLabel = new javax.swing.JLabel();
        vehicleSelectComboBox = new javax.swing.JComboBox<>();
        vehicleSelectLabel = new javax.swing.JLabel();
        lineNameTextField = new javax.swing.JTextField();
        lineNameLabel = new javax.swing.JLabel();
        averageSpeedLabel = new javax.swing.JLabel();
        capacityLabel = new javax.swing.JLabel();
        fullPriceLabel = new javax.swing.JLabel();
        reducedPriceLabel = new javax.swing.JLabel();
        reducedPriceSpinner = new javax.swing.JSpinner();
        fullPriceSpinner = new javax.swing.JSpinner();
        capacitySpinner = new javax.swing.JSpinner();
        averageSpeedSpinner = new javax.swing.JSpinner();
        addRouteButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add New Route - CityLink");

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        addNewRouteLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addNewRouteLabel.setText("Add New Route");

        vehicleSelectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bus", "Metro", "Tram", "Ferry" }));

        vehicleSelectLabel.setText("Vehicle");

        lineNameTextField.addActionListener(this::lineNameTextFieldActionPerformed);

        lineNameLabel.setText("Line Name");

        averageSpeedLabel.setText("Average Speed (km/h)");

        capacityLabel.setText("Capacity");

        fullPriceLabel.setText("Full Price (₺)");

        reducedPriceLabel.setText("Reduced Price (₺)");

        reducedPriceSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.5d));

        fullPriceSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.5d));

        capacitySpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        averageSpeedSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.5d));

        addRouteButton.setText("Add Route");
        addRouteButton.addActionListener(this::addRouteButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(capacitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lineNameTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(addRouteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fullPriceSpinner))
                                .addGap(10, 10, 10))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(vehicleSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(capacityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fullPriceLabel)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(vehicleSelectLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lineNameLabel)
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(averageSpeedSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reducedPriceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(44, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reducedPriceLabel)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(averageSpeedLabel)
                        .addGap(26, 26, 26))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 129, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(addNewRouteLabel)
                                .addGap(132, 132, 132))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(addNewRouteLabel)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleSelectLabel)
                    .addComponent(lineNameLabel)
                    .addComponent(averageSpeedLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lineNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(averageSpeedSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capacityLabel)
                    .addComponent(fullPriceLabel)
                    .addComponent(reducedPriceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reducedPriceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullPriceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(addRouteButton)
                .addGap(19, 19, 19)
                .addComponent(backButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        AdminMenu adminMenu = new AdminMenu();
        adminMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void lineNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lineNameTextFieldActionPerformed

    private void addRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRouteButtonActionPerformed
        // TODO add your handling code here:
        String vehicleType = vehicleSelectComboBox.getSelectedItem().toString();
        String lineName = lineNameTextField.getText();
        int capacity = Integer.parseInt(capacitySpinner.getValue().toString());
        double avgSpeed = Double.parseDouble(averageSpeedSpinner.getValue().toString());
        double fullPrice = Double.parseDouble(fullPriceSpinner.getValue().toString());
        double reducedPrice = Double.parseDouble(reducedPriceSpinner.getValue().toString());
        
        if (lineName.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a line name.");
        }
        
        String record = vehicleType + ";" + lineName + ";" + avgSpeed + ";" + capacity + ";" + fullPrice + ";" + reducedPrice;
        System.out.println(record);
        
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("routes.txt", true))) {
            writer.write(record);
            writer.newLine();
            javax.swing.JOptionPane.showMessageDialog(this, vehicleType + " route " + lineName + " has been saved successfully.");
            
            vehicleSelectComboBox.setSelectedItem("Bus");
            lineNameTextField.setText("");
            capacitySpinner.setValue(0);
            averageSpeedSpinner.setValue(0);
            fullPriceSpinner.setValue(0);
            reducedPriceSpinner.setValue(0);
             
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "File Error: " + e.getMessage());
            
        }
        
    }//GEN-LAST:event_addRouteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddNewRoute().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addNewRouteLabel;
    private javax.swing.JButton addRouteButton;
    private javax.swing.JLabel averageSpeedLabel;
    private javax.swing.JSpinner averageSpeedSpinner;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel capacityLabel;
    private javax.swing.JSpinner capacitySpinner;
    private javax.swing.JLabel fullPriceLabel;
    private javax.swing.JSpinner fullPriceSpinner;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lineNameLabel;
    private javax.swing.JTextField lineNameTextField;
    private javax.swing.JLabel reducedPriceLabel;
    private javax.swing.JSpinner reducedPriceSpinner;
    private javax.swing.JComboBox<String> vehicleSelectComboBox;
    private javax.swing.JLabel vehicleSelectLabel;
    // End of variables declaration//GEN-END:variables
}
