/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package citylink;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author burak
 */
public class AddScheduleInfo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddScheduleInfo.class.getName());
    VehicleDropdownManager manager = new VehicleDropdownManager();

    /**
     * Creates new form AddScheduleInfo
     */
    public AddScheduleInfo() {
        initComponents();
        
        vehicleSelectorComboBox.setModel(manager.getDropdownModel("routes.txt"));
        
        if (vehicleSelectorComboBox.getSelectedItem() != null) {
            String initialVehicle = vehicleSelectorComboBox.getSelectedItem().toString();
            lineSelectorComboBox.setModel(manager.getLineDropdownModel("routes.txt", initialVehicle));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addScheduleInfoLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        backButton = new javax.swing.JButton();
        vehicleSelectorComboBox = new javax.swing.JComboBox<>();
        vehicleLabel = new javax.swing.JLabel();
        lineSelectorComboBox = new javax.swing.JComboBox<>();
        lineLabel = new javax.swing.JLabel();
        addScheduleInfoButton = new javax.swing.JButton();
        rushHourWaitTimeLabel = new javax.swing.JLabel();
        regularHourWaitTimeLabel = new javax.swing.JLabel();
        firstVehicleTimeLabel = new javax.swing.JLabel();
        lastVehicleTimeLabel = new javax.swing.JLabel();
        rushHourWaitTimeSpinner = new javax.swing.JSpinner();
        regularHourWaitTimeSpinner = new javax.swing.JSpinner();
        firstVehicleTimeHourComboBox = new javax.swing.JComboBox<>();
        firstVehicleTimeMinuteComboBox = new javax.swing.JComboBox<>();
        lastVehicleTimeHourComboBox = new javax.swing.JComboBox<>();
        lastVehicleTimeMinuteComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Schedule Info - CityLink");

        addScheduleInfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addScheduleInfoLabel.setText("Add Schedule Info");

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        vehicleSelectorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bus", "Metro", "Tram", "Ferry" }));
        vehicleSelectorComboBox.addActionListener(this::vehicleSelectorComboBoxActionPerformed);

        vehicleLabel.setText("Vehicle");

        lineSelectorComboBox.addActionListener(this::lineSelectorComboBoxActionPerformed);

        lineLabel.setText("Line");

        addScheduleInfoButton.setText("Add Schedule Info");
        addScheduleInfoButton.addActionListener(this::addScheduleInfoButtonActionPerformed);

        rushHourWaitTimeLabel.setText("Rush Hour Wait Time (mins)");

        regularHourWaitTimeLabel.setText("Regular Hour Wait Time (mins)");

        firstVehicleTimeLabel.setText("First Vehicle Time");

        lastVehicleTimeLabel.setText("Last Vehicle Time");

        rushHourWaitTimeSpinner.setModel(new javax.swing.SpinnerNumberModel(0.5d, 0.5d, 100.0d, 0.5d));

        regularHourWaitTimeSpinner.setModel(new javax.swing.SpinnerNumberModel(0.5d, 0.5d, 100.0d, 0.5d));

        firstVehicleTimeHourComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        firstVehicleTimeMinuteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        lastVehicleTimeHourComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        lastVehicleTimeMinuteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(addScheduleInfoButton)
                                .addGap(45, 45, 45)
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(addScheduleInfoLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(vehicleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lineLabel)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(vehicleSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(rushHourWaitTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(firstVehicleTimeHourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstVehicleTimeMinuteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lineSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(regularHourWaitTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lastVehicleTimeHourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastVehicleTimeMinuteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(rushHourWaitTimeLabel)
                .addGap(32, 32, 32)
                .addComponent(regularHourWaitTimeLabel)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(firstVehicleTimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lastVehicleTimeLabel)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(addScheduleInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleLabel)
                    .addComponent(lineLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lineSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstVehicleTimeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lastVehicleTimeLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(regularHourWaitTimeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(regularHourWaitTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(backButton)
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(addScheduleInfoButton)
                                        .addGap(29, 29, 29))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rushHourWaitTimeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rushHourWaitTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstVehicleTimeHourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstVehicleTimeMinuteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastVehicleTimeHourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastVehicleTimeMinuteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        AdminMenu adminMenu = new AdminMenu();
        adminMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void vehicleSelectorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleSelectorComboBoxActionPerformed
        // TODO add your handling code here:
        String selectedVehicle = vehicleSelectorComboBox.getSelectedItem().toString();

        DefaultComboBoxModel<String> lineModel = manager.getLineDropdownModel("routes.txt", selectedVehicle);

        lineSelectorComboBox.setModel(lineModel);

    }//GEN-LAST:event_vehicleSelectorComboBoxActionPerformed

    private void lineSelectorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineSelectorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lineSelectorComboBoxActionPerformed

    private void addScheduleInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addScheduleInfoButtonActionPerformed
        // TODO add your handling code here:
        String vehicleType = (String) vehicleSelectorComboBox.getSelectedItem();
        String lineName = (String) lineSelectorComboBox.getSelectedItem();
        String firstVehicleTimeHour = (String) firstVehicleTimeHourComboBox.getSelectedItem();
        String firstVehicleTimeMinute = (String) firstVehicleTimeMinuteComboBox.getSelectedItem();
        String lastVehicleTimeHour = (String) lastVehicleTimeHourComboBox.getSelectedItem();
        String lastVehicleTimeMinute = (String) lastVehicleTimeMinuteComboBox.getSelectedItem();
        double rushHourWaitTime = (double) rushHourWaitTimeSpinner.getValue();
        double regularHourWaitTime = (double) regularHourWaitTimeSpinner.getValue();
        String firstVehicleTime = firstVehicleTimeHour + "." + firstVehicleTimeMinute;
        String lastVehicleTime = lastVehicleTimeHour + "." + lastVehicleTimeMinute;
        
        
        
        String record = vehicleType + ";" + lineName + ";" + firstVehicleTime + ";" + lastVehicleTime + ";" + rushHourWaitTime + ";" + regularHourWaitTime;
        System.out.println(record);
        
        if (vehicleType == null || vehicleType.isEmpty() || lineName == null || lineName.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "There is no routes added to system. To use this tool, please add a route to the system.");
        }
        
        else {
            try (BufferedWriter writer = new BufferedWriter(new FileWriter("schedules.txt", true))) {
            writer.write(record);
            writer.newLine();
            javax.swing.JOptionPane.showMessageDialog(this, "The schedule info about " + vehicleType + " route " + lineName + " has been added.");
            
            vehicleSelectorComboBox.setSelectedItem("Bus");
            lineSelectorComboBox.setSelectedItem("");
            firstVehicleTimeHourComboBox.setSelectedItem("00");
            firstVehicleTimeMinuteComboBox.setSelectedItem("00");
            lastVehicleTimeHourComboBox.setSelectedItem("00");
            lastVehicleTimeMinuteComboBox.setSelectedItem("00");
            rushHourWaitTimeSpinner.setValue(0.5);
            regularHourWaitTimeSpinner.setValue(0.5);
            
             
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "File Error: " + e.getMessage());
            
        }
        
        }
    }//GEN-LAST:event_addScheduleInfoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddScheduleInfo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addScheduleInfoButton;
    private javax.swing.JLabel addScheduleInfoLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> firstVehicleTimeHourComboBox;
    private javax.swing.JLabel firstVehicleTimeLabel;
    private javax.swing.JComboBox<String> firstVehicleTimeMinuteComboBox;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> lastVehicleTimeHourComboBox;
    private javax.swing.JLabel lastVehicleTimeLabel;
    private javax.swing.JComboBox<String> lastVehicleTimeMinuteComboBox;
    private javax.swing.JLabel lineLabel;
    private javax.swing.JComboBox<String> lineSelectorComboBox;
    private javax.swing.JLabel regularHourWaitTimeLabel;
    private javax.swing.JSpinner regularHourWaitTimeSpinner;
    private javax.swing.JLabel rushHourWaitTimeLabel;
    private javax.swing.JSpinner rushHourWaitTimeSpinner;
    private javax.swing.JLabel vehicleLabel;
    private javax.swing.JComboBox<String> vehicleSelectorComboBox;
    // End of variables declaration//GEN-END:variables
}
