/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package citylink;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author burak
 */
public class AddServiceAlerts extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddServiceAlerts.class.getName());
    VehicleDropdownManager manager = new VehicleDropdownManager();

    /**
     * Creates new form AddServiceAlerts
     */
    public AddServiceAlerts() {
        initComponents();
        
        vehicleSelectorComboBox.setModel(manager.getDropdownModel("routes.txt"));
        
        if (vehicleSelectorComboBox.getSelectedItem() != null) {
            String initialVehicle = vehicleSelectorComboBox.getSelectedItem().toString();
            lineSelectorComboBox.setModel(manager.getLineDropdownModel("routes.txt", initialVehicle));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        addServiceAlertsLabel = new javax.swing.JLabel();
        alertMessageLabel = new javax.swing.JLabel();
        startDateSpinner = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        alertMessageTextArea = new javax.swing.JTextArea();
        vehicleSelectorComboBox = new javax.swing.JComboBox<>();
        lineSelectorComboBox = new javax.swing.JComboBox<>();
        endDateSpinner = new javax.swing.JSpinner();
        vehicleLabel = new javax.swing.JLabel();
        lineLabel = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        sendAlertMessageButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Service Alerts - CityLink");

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        addServiceAlertsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addServiceAlertsLabel.setText("Add Service Alerts");

        alertMessageLabel.setText("Alert Message");

        startDateSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));

        alertMessageTextArea.setColumns(20);
        alertMessageTextArea.setRows(5);
        jScrollPane1.setViewportView(alertMessageTextArea);

        vehicleSelectorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bus", "Metro", "Tram", "Ferry" }));
        vehicleSelectorComboBox.addActionListener(this::vehicleSelectorComboBoxActionPerformed);

        lineSelectorComboBox.addActionListener(this::lineSelectorComboBoxActionPerformed);

        endDateSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));

        vehicleLabel.setText("Vehicle");

        lineLabel.setText("Line");

        startDateLabel.setText("Start Date");

        endDateLabel.setText("End Date");

        sendAlertMessageButton.setText("Send Alert Message");
        sendAlertMessageButton.addActionListener(this::sendAlertMessageButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lineSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(endDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(vehicleSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(startDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lineLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(endDateLabel)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(vehicleLabel)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(startDateLabel)
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alertMessageLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(addServiceAlertsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sendAlertMessageButton)
                        .addGap(43, 43, 43)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(addServiceAlertsLabel)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleLabel)
                    .addComponent(startDateLabel))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vehicleSelectorComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lineLabel)
                    .addComponent(endDateLabel))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lineSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alertMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(sendAlertMessageButton)
                        .addContainerGap(18, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        AdminMenu adminMenu = new AdminMenu();
        adminMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void vehicleSelectorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleSelectorComboBoxActionPerformed
        // TODO add your handling code here:
        String selectedVehicle = vehicleSelectorComboBox.getSelectedItem().toString();
        
        DefaultComboBoxModel<String> lineModel = manager.getLineDropdownModel("routes.txt", selectedVehicle);
        
        lineSelectorComboBox.setModel(lineModel);
        
    }//GEN-LAST:event_vehicleSelectorComboBoxActionPerformed

    private void lineSelectorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineSelectorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lineSelectorComboBoxActionPerformed

    private void sendAlertMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendAlertMessageButtonActionPerformed
        // TODO add your handling code here:
        String vehicleType = (String) vehicleSelectorComboBox.getSelectedItem();
        String lineName = (String) lineSelectorComboBox.getSelectedItem();
        String startDate = startDateSpinner.getValue().toString();
        String endDate = endDateSpinner.getValue().toString();
        String alertMessage = alertMessageTextArea.getText();
        
        String record = vehicleType + ";" + lineName + ";" + startDate + ";" + endDate + ";" + alertMessage;
        System.out.println(record);
        
        if (vehicleType == null || vehicleType.isEmpty() || lineName == null || lineName.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "There is no routes added to system. To use this tool, please add a route to the system.");
        }
        else if (alertMessage.isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter an alert message.");
        }
        
        else {
            try (BufferedWriter writer = new BufferedWriter(new FileWriter("servicealerts.txt", true))) {
            writer.write(record);
            writer.newLine();
            javax.swing.JOptionPane.showMessageDialog(this, "An alert message about " + vehicleType + " route " + lineName + " has been added.");
            
            vehicleSelectorComboBox.setSelectedItem("Bus");
            lineSelectorComboBox.setSelectedItem("");
            startDateSpinner.setValue(new java.util.Date());
            endDateSpinner.setValue(new java.util.Date());
            alertMessageTextArea.setText("");
             
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "File Error: " + e.getMessage());
            
        }
        
        }
    }//GEN-LAST:event_sendAlertMessageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddServiceAlerts().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addServiceAlertsLabel;
    private javax.swing.JLabel alertMessageLabel;
    private javax.swing.JTextArea alertMessageTextArea;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JSpinner endDateSpinner;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lineLabel;
    private javax.swing.JComboBox<String> lineSelectorComboBox;
    private javax.swing.JButton sendAlertMessageButton;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JSpinner startDateSpinner;
    private javax.swing.JLabel vehicleLabel;
    private javax.swing.JComboBox<String> vehicleSelectorComboBox;
    // End of variables declaration//GEN-END:variables
}
