/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package citylink;

/**
 *
 * @author burak
 */
public class AdminMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminMenu.class.getName());

    /**
     * Creates new form AdminPanel
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        addServiceAlertsButton = new javax.swing.JButton();
        addNewRouteButton = new javax.swing.JButton();
        removeExistingRoutesButton = new javax.swing.JButton();
        removeServiceAlertsButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        addScheduleInfoButton = new javax.swing.JButton();
        removeScheduleInfoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Menu - CityLink");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Admin Menu");

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        addServiceAlertsButton.setText("Add Service Alerts");
        addServiceAlertsButton.addActionListener(this::addServiceAlertsButtonActionPerformed);

        addNewRouteButton.setText("Add New Route");
        addNewRouteButton.addActionListener(this::addNewRouteButtonActionPerformed);

        removeExistingRoutesButton.setText("Remove Existing Routes");
        removeExistingRoutesButton.addActionListener(this::removeExistingRoutesButtonActionPerformed);

        removeServiceAlertsButton.setText("Remove Service Alerts");
        removeServiceAlertsButton.addActionListener(this::removeServiceAlertsButtonActionPerformed);

        addScheduleInfoButton.setText("Add Schedule Info");
        addScheduleInfoButton.addActionListener(this::addScheduleInfoButtonActionPerformed);

        removeScheduleInfoButton.setText("Remove Schedule Info");
        removeScheduleInfoButton.addActionListener(this::removeScheduleInfoButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addScheduleInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addNewRouteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(addServiceAlertsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(removeExistingRoutesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(removeServiceAlertsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(removeScheduleInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNewRouteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeExistingRoutesButton)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addServiceAlertsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeServiceAlertsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addScheduleInfoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeScheduleInfoButton)
                        .addContainerGap(38, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        MainMenu mainMenu = new MainMenu();
        mainMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void addServiceAlertsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addServiceAlertsButtonActionPerformed
        // TODO add your handling code here:
        AddServiceAlerts addServiceAlertsMenu = new AddServiceAlerts();
        addServiceAlertsMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addServiceAlertsButtonActionPerformed

    private void addNewRouteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewRouteButtonActionPerformed
        // TODO add your handling code here:
        AddNewRoute addNewRouteMenu = new AddNewRoute();
        addNewRouteMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addNewRouteButtonActionPerformed

    private void removeExistingRoutesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeExistingRoutesButtonActionPerformed
        // TODO add your handling code here:
        RemoveExistingRoutes removeExistingRoutesMenu = new RemoveExistingRoutes();
        removeExistingRoutesMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_removeExistingRoutesButtonActionPerformed

    private void removeServiceAlertsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeServiceAlertsButtonActionPerformed
        // TODO add your handling code here:
        RemoveServiceAlerts removeServiceAlerts = new RemoveServiceAlerts();
        removeServiceAlerts.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_removeServiceAlertsButtonActionPerformed

    private void addScheduleInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addScheduleInfoButtonActionPerformed
        // TODO add your handling code here:
        AddScheduleInfo addScheduleInfo = new AddScheduleInfo();
        addScheduleInfo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addScheduleInfoButtonActionPerformed

    private void removeScheduleInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeScheduleInfoButtonActionPerformed
        // TODO add your handling code here:
        RemoveScheduleInfo removeScheduleInfo = new RemoveScheduleInfo();
        removeScheduleInfo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_removeScheduleInfoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewRouteButton;
    private javax.swing.JButton addScheduleInfoButton;
    private javax.swing.JButton addServiceAlertsButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton removeExistingRoutesButton;
    private javax.swing.JButton removeScheduleInfoButton;
    private javax.swing.JButton removeServiceAlertsButton;
    // End of variables declaration//GEN-END:variables
}
