/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package citylink;

/**
 *
 * @author burak
 */
public class BuySubscriptions extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BuySubscriptions.class.getName());

    /**
     * Creates new form BuySubscriptions
     */
    public BuySubscriptions() {
        initComponents();
        
        calculatePrice();
    }
    
    double totalPrice;
    
    private void calculatePrice(){
        String purchaseType = subscriptionTypeComboBox.getSelectedItem().toString();
        String passengerType = passengerTypeComboBox.getSelectedItem().toString();
        
        if (passengerType.equals("Adult")) {
            if (purchaseType.equals("Daily Pass")) {
                totalPrice = 200.00;
            }
            else if (purchaseType.equals("Weekly Pass")) {
                totalPrice = 800.00;
                
            }
            else if (purchaseType.equals("Monthly Pass")) {
                totalPrice = 2500.00;
            }
            
        }
        else { //reduced prices %50 off
            if (purchaseType.equals("Daily Pass")) {
                totalPrice = 100.00;
            }
            else if (purchaseType.equals("Weekly Pass")) {
                totalPrice = 400.00;
                
            }
            else if (purchaseType.equals("Monthly Pass")) {
                totalPrice = 1250.00;
            }
            
        }
        
        totalPriceText.setText(String.format("₺%.2f", totalPrice));
        
        
    }
    
    private void validateUserID(String userID, boolean isValid) throws InvalidUserIDException {
        
        if (userID == null || userID.isBlank() || userID.length() < 11) {
            throw new InvalidUserIDException("Please enter a 11-digit user ID number.", false);
        }

        if (!isValid) {
            throw new InvalidUserIDException("The user ID number you entered is not a real user ID number. Please enter a real user ID number.", true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buyPassesAndSubscriptionsLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        backButton = new javax.swing.JButton();
        descText1 = new javax.swing.JLabel();
        descText2 = new javax.swing.JLabel();
        subscriptionTypeComboBox = new javax.swing.JComboBox<>();
        subscriptionTypeLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        totalPriceText = new javax.swing.JLabel();
        userIDNumberTextField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        proceedToPaymentButton = new javax.swing.JButton();
        passengerTypeComboBox = new javax.swing.JComboBox<>();
        passengerTypeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buy Passes & Subscriptions - CityLink");

        buyPassesAndSubscriptionsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buyPassesAndSubscriptionsLabel.setText("Buy Passes & Subscriptions");

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        descText1.setText("One subscription, every vehicle and line, unlimited rides.");

        descText2.setText("Subscriptions starts at the moment the payment is completed.");

        subscriptionTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daily Pass", "Weekly Pass", "Monthly Pass" }));
        subscriptionTypeComboBox.addActionListener(this::subscriptionTypeComboBoxActionPerformed);

        subscriptionTypeLabel.setText("Subscription Type");

        totalLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalLabel.setText("Total:");

        totalPriceText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalPriceText.setText("₺0.0");

        try {
            userIDNumberTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        userIDNumberTextField.addActionListener(this::userIDNumberTextFieldActionPerformed);

        jLabel5.setText("User ID Number");

        proceedToPaymentButton.setText("Proceed to Payment");
        proceedToPaymentButton.addActionListener(this::proceedToPaymentButtonActionPerformed);

        passengerTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adult", "Student", "Teacher", "65+", "Disabled" }));
        passengerTypeComboBox.addActionListener(this::passengerTypeComboBoxActionPerformed);

        passengerTypeLabel.setText("Passenger Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descText2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(subscriptionTypeLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(subscriptionTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(passengerTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(passengerTypeLabel)
                                .addGap(31, 31, 31)))))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buyPassesAndSubscriptionsLabel)
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(descText1)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(proceedToPaymentButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(userIDNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(totalLabel)))
                .addGap(16, 16, 16)
                .addComponent(totalPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(buyPassesAndSubscriptionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subscriptionTypeLabel)
                    .addComponent(passengerTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subscriptionTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passengerTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIDNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLabel)
                    .addComponent(totalPriceText))
                .addGap(18, 18, 18)
                .addComponent(proceedToPaymentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descText2)
                .addGap(4, 4, 4)
                .addComponent(backButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        PassengerMenu passengerMenu = new PassengerMenu();
        passengerMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void userIDNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIDNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIDNumberTextFieldActionPerformed

    private void proceedToPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedToPaymentButtonActionPerformed
        // TODO add your handling code here:
        String userID = userIDNumberTextField.getText();
        boolean isValid = UserIDValidator.isValid(userID);
        System.out.println(isValid);

        try {
            validateUserID(userID, isValid);

            String purchaseType = subscriptionTypeComboBox.getSelectedItem().toString();
            String passengerType = passengerTypeComboBox.getSelectedItem().toString();
            int amount = 1;
            String vehicleType = null;
            String lineName = null;

            PaymentPage paymentPage = new PaymentPage(totalPrice, userID, amount, vehicleType, lineName, passengerType, purchaseType);
            paymentPage.setVisible(true);
            this.setVisible(false);

        

        } catch (InvalidUserIDException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());

            if (ex.isShouldClearField()) {
                userIDNumberTextField.setValue(null);
            }
            
            userIDNumberTextField.requestFocusInWindow();
        }

    }//GEN-LAST:event_proceedToPaymentButtonActionPerformed

    private void passengerTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengerTypeComboBoxActionPerformed
        // TODO add your handling code here:
        calculatePrice();
    }//GEN-LAST:event_passengerTypeComboBoxActionPerformed

    private void subscriptionTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscriptionTypeComboBoxActionPerformed
        // TODO add your handling code here:
        calculatePrice();
    }//GEN-LAST:event_subscriptionTypeComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BuySubscriptions().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel buyPassesAndSubscriptionsLabel;
    private javax.swing.JLabel descText1;
    private javax.swing.JLabel descText2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> passengerTypeComboBox;
    private javax.swing.JLabel passengerTypeLabel;
    private javax.swing.JButton proceedToPaymentButton;
    private javax.swing.JComboBox<String> subscriptionTypeComboBox;
    private javax.swing.JLabel subscriptionTypeLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalPriceText;
    private javax.swing.JFormattedTextField userIDNumberTextField;
    // End of variables declaration//GEN-END:variables
}
