/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package citylink;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author burak
 */
public class BuyTickets extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BuyTickets.class.getName());
    VehicleDropdownManager manager = new VehicleDropdownManager();

    /**
     * Creates new form BuyTickets
     */
    public BuyTickets() {
        initComponents();
        
        totalPriceText.setVisible(false);
        
        

        vehicleSelectorComboBox.setModel(manager.getDropdownModel("routes.txt"));

        if (vehicleSelectorComboBox.getSelectedItem() != null) {
            String initialVehicle = vehicleSelectorComboBox.getSelectedItem().toString();
            lineSelectorComboBox.setModel(manager.getLineDropdownModel("routes.txt", initialVehicle));
        }
        
        calculatePrice();

    }
    
    double totalPrice;
    
    
    private void calculatePrice(){
        if (vehicleSelectorComboBox.getSelectedItem() == null || lineSelectorComboBox.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "There is no existing route available to calculate prices.");
            return;
        }
        
        
        double price;
        String vehicleType = vehicleSelectorComboBox.getSelectedItem().toString();
        String lineName = lineSelectorComboBox.getSelectedItem().toString();
        String passengerType = passengerTypeComboBox.getSelectedItem().toString();
        int amount = (Integer) amountSpinner.getValue();
            
        boolean routeFound = false;
        try (BufferedReader reader = new BufferedReader(new FileReader("routes.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(";");

                if (parts.length >= 6 && parts[0].equals(vehicleType) && parts[1].equals(lineName)) {
                    String fullPrice = parts[4];
                    String reducedPrice = parts[5];

                    if (passengerType.equals("Adult")){
                        price = Double.parseDouble(fullPrice);

                    } else {
                        price = Double.parseDouble(reducedPrice);
                    }
                    
                    totalPrice = price * amount;
                    
                    totalPriceText.setText(String.format("₺%.2f", totalPrice));
                    totalPriceText.setVisible(true);
                    
                routeFound = true;
                break;
                
            }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error occured in reading file: " + e.getMessage());
        }
        
        

        if (!routeFound){
            JOptionPane.showMessageDialog(this, "Price information for the selected route cannot be found.");
        }
    }
    
    private void validateUserID(String userID, boolean isValid) throws InvalidUserIDException {
        
        if (userID == null || userID.isBlank() || userID.length() < 11) {
            throw new InvalidUserIDException("Please enter a 11-digit user ID number.", false);
        }

        if (!isValid) {
            throw new InvalidUserIDException("The user ID number you entered is not a real user ID number. Please enter a real user ID number.", true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        vehicleSelectorComboBox = new javax.swing.JComboBox<>();
        passengerTypeComboBox = new javax.swing.JComboBox<>();
        lineSelectorComboBox = new javax.swing.JComboBox<>();
        vehicleTypeLabel = new javax.swing.JLabel();
        lineNameLabel = new javax.swing.JLabel();
        passengerTypeLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        proceedToPaymentButton = new javax.swing.JButton();
        calculateFaresLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        userIDNumberTextField = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        amountSpinner = new javax.swing.JSpinner();
        amountLabel = new javax.swing.JLabel();
        totalPriceText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculate Fares - CityLink");

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        vehicleSelectorComboBox.addActionListener(this::vehicleSelectorComboBoxActionPerformed);

        passengerTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adult", "Student", "Teacher", "65+", "Disabled" }));
        passengerTypeComboBox.addActionListener(this::passengerTypeComboBoxActionPerformed);

        lineSelectorComboBox.addActionListener(this::lineSelectorComboBoxActionPerformed);

        vehicleTypeLabel.setText("Vehicle Type");

        lineNameLabel.setText("Line Name");

        passengerTypeLabel.setText("Passenger Type");

        totalLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalLabel.setText("Total:");

        proceedToPaymentButton.setText("Proceed to Payment");
        proceedToPaymentButton.addActionListener(this::proceedToPaymentButtonActionPerformed);

        calculateFaresLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        calculateFaresLabel.setText("Buy Tickets");

        jLabel1.setText("User ID Number");

        try {
            userIDNumberTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        userIDNumberTextField.addActionListener(this::userIDNumberTextFieldActionPerformed);

        amountSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        amountSpinner.addChangeListener(this::amountSpinnerStateChanged);
        amountSpinner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amountSpinnerMouseClicked(evt);
            }
        });

        amountLabel.setText("Amount");

        totalPriceText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalPriceText.setText("₺0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(proceedToPaymentButton)
                                .addGap(125, 125, 125))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(amountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(amountSpinner)
                                .addGap(82, 82, 82)
                                .addComponent(userIDNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(vehicleTypeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lineNameLabel)
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passengerTypeLabel)
                                    .addComponent(passengerTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vehicleSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calculateFaresLabel)
                            .addComponent(lineSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(119, 119, 119))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(calculateFaresLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleTypeLabel)
                    .addComponent(lineNameLabel)
                    .addComponent(passengerTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passengerTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lineSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(amountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIDNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel)
                    .addComponent(totalPriceText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(proceedToPaymentButton)
                .addGap(4, 4, 4)
                .addComponent(backButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        PassengerMenu passengerMenu = new PassengerMenu();
        passengerMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void vehicleSelectorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleSelectorComboBoxActionPerformed
        // TODO add your handling code here:
        String selectedVehicle = vehicleSelectorComboBox.getSelectedItem().toString();

        DefaultComboBoxModel<String> lineModel = manager.getLineDropdownModel("routes.txt", selectedVehicle);

        lineSelectorComboBox.setModel(lineModel);
        
        calculatePrice();
    }//GEN-LAST:event_vehicleSelectorComboBoxActionPerformed

  
    private void passengerTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengerTypeComboBoxActionPerformed
        // TODO add your handling code here:
        calculatePrice();
    }//GEN-LAST:event_passengerTypeComboBoxActionPerformed

    private void lineSelectorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineSelectorComboBoxActionPerformed
        // TODO add your handling code here:
        calculatePrice();
    }//GEN-LAST:event_lineSelectorComboBoxActionPerformed

    private void proceedToPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedToPaymentButtonActionPerformed
        // TODO add your handling code here:
        String userID = userIDNumberTextField.getText();
        boolean isValid = UserIDValidator.isValid(userID);
        System.out.println(isValid);
        
        try {
            validateUserID(userID, isValid);

            String vehicleType = vehicleSelectorComboBox.getSelectedItem().toString();
            String lineName = lineSelectorComboBox.getSelectedItem().toString();
            String passengerType = passengerTypeComboBox.getSelectedItem().toString();
            int amount = (Integer) amountSpinner.getValue();
            String purchaseType = "Single Ride";
            
            PaymentPage paymentPage = new PaymentPage(totalPrice, userID, amount, vehicleType, lineName, passengerType, purchaseType);
            paymentPage.setVisible(true);
            this.setVisible(false);

        

        } catch (InvalidUserIDException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());

            if (ex.isShouldClearField()) {
                userIDNumberTextField.setValue(null);
            }
            
            userIDNumberTextField.requestFocusInWindow();
        }

    }//GEN-LAST:event_proceedToPaymentButtonActionPerformed

    private void userIDNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIDNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIDNumberTextFieldActionPerformed

    private void amountSpinnerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amountSpinnerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_amountSpinnerMouseClicked

    private void amountSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_amountSpinnerStateChanged
        // TODO add your handling code here:
        calculatePrice();

    }//GEN-LAST:event_amountSpinnerStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BuyTickets().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JSpinner amountSpinner;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel calculateFaresLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lineNameLabel;
    private javax.swing.JComboBox<String> lineSelectorComboBox;
    private javax.swing.JComboBox<String> passengerTypeComboBox;
    private javax.swing.JLabel passengerTypeLabel;
    private javax.swing.JButton proceedToPaymentButton;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalPriceText;
    private javax.swing.JFormattedTextField userIDNumberTextField;
    private javax.swing.JComboBox<String> vehicleSelectorComboBox;
    private javax.swing.JLabel vehicleTypeLabel;
    // End of variables declaration//GEN-END:variables
}
