/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package citylink;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author burak
 */
public class CalculateFares extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculateFares.class.getName());
    VehicleDropdownManager manager = new VehicleDropdownManager();
    
    /**
     * Creates new form CalculateFares
     */
    public CalculateFares() {
        initComponents();
        
        calculatedPriceText.setVisible(false);
        
        vehicleSelectorComboBox.setModel(manager.getDropdownModel("routes.txt"));
        
        if (vehicleSelectorComboBox.getSelectedItem() != null) {
            String initialVehicle = vehicleSelectorComboBox.getSelectedItem().toString();
            lineSelectorComboBox.setModel(manager.getLineDropdownModel("routes.txt", initialVehicle));
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        vehicleSelectorComboBox = new javax.swing.JComboBox<>();
        passengerTypeComboBox = new javax.swing.JComboBox<>();
        lineSelectorComboBox = new javax.swing.JComboBox<>();
        vehicleTypeLabel = new javax.swing.JLabel();
        lineNameLabel = new javax.swing.JLabel();
        passengerTypeLabel = new javax.swing.JLabel();
        calculatedPriceLabel = new javax.swing.JLabel();
        calculatePriceButton = new javax.swing.JButton();
        calculateFaresLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        calculatedPriceText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculate Fares - CityLink");

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        vehicleSelectorComboBox.addActionListener(this::vehicleSelectorComboBoxActionPerformed);

        passengerTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adult", "Student", "Teacher", "65+", "Disabled" }));
        passengerTypeComboBox.addActionListener(this::passengerTypeComboBoxActionPerformed);

        lineSelectorComboBox.addActionListener(this::lineSelectorComboBoxActionPerformed);

        vehicleTypeLabel.setText("Vehicle Type");

        lineNameLabel.setText("Line Name");

        passengerTypeLabel.setText("Passenger Type");

        calculatedPriceLabel.setText("Ticket Price for Selected Route and Passenger:");

        calculatePriceButton.setText("Calculate Price");
        calculatePriceButton.addActionListener(this::calculatePriceButtonActionPerformed);

        calculateFaresLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        calculateFaresLabel.setText("Calculate Fares");

        calculatedPriceText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        calculatedPriceText.setText("₺0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(vehicleTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lineNameLabel)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passengerTypeLabel)
                    .addComponent(passengerTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(calculateFaresLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(calculatedPriceLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(calculatedPriceText)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(vehicleSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculatePriceButton)
                    .addComponent(lineSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(calculateFaresLabel)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleTypeLabel)
                    .addComponent(lineNameLabel)
                    .addComponent(passengerTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passengerTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lineSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(calculatePriceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calculatedPriceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calculatedPriceText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(backButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        PassengerMenu passengerMenu = new PassengerMenu();
        passengerMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void vehicleSelectorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleSelectorComboBoxActionPerformed
        // TODO add your handling code here:
        String selectedVehicle = vehicleSelectorComboBox.getSelectedItem().toString();
        
        DefaultComboBoxModel<String> lineModel = manager.getLineDropdownModel("routes.txt", selectedVehicle);
        
        lineSelectorComboBox.setModel(lineModel);
    }//GEN-LAST:event_vehicleSelectorComboBoxActionPerformed

    private void passengerTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengerTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passengerTypeComboBoxActionPerformed

    private void lineSelectorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineSelectorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lineSelectorComboBoxActionPerformed

    private void calculatePriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatePriceButtonActionPerformed
        // TODO add your handling code here:
        if (vehicleSelectorComboBox.getSelectedItem() == null || lineSelectorComboBox.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "There is no existing route available to calculate prices.");
            return;
        }
        
        double price;
        String vehicleType = vehicleSelectorComboBox.getSelectedItem().toString();
        String lineName = lineSelectorComboBox.getSelectedItem().toString();
        String passengerType = passengerTypeComboBox.getSelectedItem().toString();
            
        boolean routeFound = false;
        try (BufferedReader reader = new BufferedReader(new FileReader("routes.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(";");

                if (parts.length >= 6 && parts[0].equals(vehicleType) && parts[1].equals(lineName)) {
                    String fullPrice = parts[4];
                    String reducedPrice = parts[5];

                    if (passengerType.equals("Adult")){
                        price = Double.parseDouble(fullPrice);

                    } else {
                        price = Double.parseDouble(reducedPrice);
                    }
                    
                    calculatedPriceText.setText(String.format("₺%.2f", price));
                    calculatedPriceText.setVisible(true);
                    
                routeFound = true;
                break;
                
            }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error occured in reading file: " + e.getMessage());
        }
        
        

        if (!routeFound){
            JOptionPane.showMessageDialog(this, "Price information for the selected route cannot be found.");
        }
     
        
    }//GEN-LAST:event_calculatePriceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculateFares().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel calculateFaresLabel;
    private javax.swing.JButton calculatePriceButton;
    private javax.swing.JLabel calculatedPriceLabel;
    private javax.swing.JLabel calculatedPriceText;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lineNameLabel;
    private javax.swing.JComboBox<String> lineSelectorComboBox;
    private javax.swing.JComboBox<String> passengerTypeComboBox;
    private javax.swing.JLabel passengerTypeLabel;
    private javax.swing.JComboBox<String> vehicleSelectorComboBox;
    private javax.swing.JLabel vehicleTypeLabel;
    // End of variables declaration//GEN-END:variables
}
