/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package citylink;

/**
 *
 * @author burak
 */
public class PassengerMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PassengerMenu.class.getName());

    /**
     * Creates new form PassangerMenu
     */
    public PassengerMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passengerMenuTitleText = new javax.swing.JLabel();
        buyTicketsButton = new javax.swing.JButton();
        calculateFaresButton = new javax.swing.JButton();
        viewServiceAlertsButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        viewRoutesButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        buyPassesAndSubscriptionsButton = new javax.swing.JButton();
        viewScheduleInfoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Passenger Menu - CityLink");

        passengerMenuTitleText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        passengerMenuTitleText.setText("Passenger Menu");

        buyTicketsButton.setText("Buy Tickets");
        buyTicketsButton.addActionListener(this::buyTicketsButtonActionPerformed);

        calculateFaresButton.setText("Calculate Fares");
        calculateFaresButton.addActionListener(this::calculateFaresButtonActionPerformed);

        viewServiceAlertsButton.setText("View Service Alerts");
        viewServiceAlertsButton.addActionListener(this::viewServiceAlertsButtonActionPerformed);

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        viewRoutesButton1.setText("View Routes");
        viewRoutesButton1.addActionListener(this::viewRoutesButton1ActionPerformed);

        buyPassesAndSubscriptionsButton.setText("Buy Passes & Subscriptions");
        buyPassesAndSubscriptionsButton.addActionListener(this::buyPassesAndSubscriptionsButtonActionPerformed);

        viewScheduleInfoButton.setText("View Schedule Info");
        viewScheduleInfoButton.addActionListener(this::viewScheduleInfoButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewScheduleInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buyPassesAndSubscriptionsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewRoutesButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passengerMenuTitleText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewServiceAlertsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calculateFaresButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buyTicketsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(104, 104, 104))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(passengerMenuTitleText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyTicketsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buyPassesAndSubscriptionsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calculateFaresButton)
                .addGap(12, 12, 12)
                .addComponent(viewServiceAlertsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewRoutesButton1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewScheduleInfoButton)
                        .addContainerGap(34, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buyTicketsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyTicketsButtonActionPerformed
        // TODO add your handling code here:
        BuyTickets buyTicketsMenu = new BuyTickets();
        buyTicketsMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buyTicketsButtonActionPerformed

    private void calculateFaresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateFaresButtonActionPerformed
        // TODO add your handling code here:
        CalculateFares calculateFaresMenu = new CalculateFares();
        calculateFaresMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_calculateFaresButtonActionPerformed

    private void viewServiceAlertsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewServiceAlertsButtonActionPerformed
        // TODO add your handling code here:
        ViewServiceAlerts viewServiceAlertsMenu = new ViewServiceAlerts();
        viewServiceAlertsMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewServiceAlertsButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        MainMenu mainMenu = new MainMenu();
        mainMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void viewRoutesButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRoutesButton1ActionPerformed
        // TODO add your handling code here:
        ViewRoutes viewRoutesMenu = new ViewRoutes();
        viewRoutesMenu.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_viewRoutesButton1ActionPerformed

    private void buyPassesAndSubscriptionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyPassesAndSubscriptionsButtonActionPerformed
        // TODO add your handling code here:
        BuySubscriptions buySubscriptions = new BuySubscriptions();
        buySubscriptions.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buyPassesAndSubscriptionsButtonActionPerformed

    private void viewScheduleInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewScheduleInfoButtonActionPerformed
        // TODO add your handling code here:
        ViewScheduleInfo viewScheduleInfo = new ViewScheduleInfo();
        viewScheduleInfo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_viewScheduleInfoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PassengerMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton buyPassesAndSubscriptionsButton;
    private javax.swing.JButton buyTicketsButton;
    private javax.swing.JButton calculateFaresButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel passengerMenuTitleText;
    private javax.swing.JButton viewRoutesButton1;
    private javax.swing.JButton viewScheduleInfoButton;
    private javax.swing.JButton viewServiceAlertsButton;
    // End of variables declaration//GEN-END:variables
}
