/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package citylink;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import javax.swing.JDialog;
import javax.swing.JOptionPane;


/**
 *
 * @author burak
 */
public class PaymentPage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaymentPage.class.getName());

    /**
     * Creates new form PaymentPage
     */
    
    private double totalPrice;
    private String userID;
    private int amount;
    private String vehicleType;
    private String lineName;
    private String passengerType;
    private String purchaseType;
    
    public PaymentPage(double totalPrice, String userID, int amount, String vehicleType, String lineName, String passengerType, String purchaseType) {
        initComponents();
        
        this.totalPrice = totalPrice;
        this.userID = userID;
        this.amount = amount;
        this.vehicleType = vehicleType;
        this.lineName = lineName;
        this.passengerType = passengerType;
        this.purchaseType = purchaseType;
        
        totalPriceText.setText(String.format("Total: ₺%.2f", totalPrice));  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        terminatePaymentButton = new javax.swing.JButton();
        paymentLabel = new javax.swing.JLabel();
        cardNumberFormattedField = new javax.swing.JFormattedTextField();
        cvcFormattedField = new javax.swing.JFormattedTextField();
        cvcLabel = new javax.swing.JLabel();
        expirationDateLabel = new javax.swing.JLabel();
        cardHolderNameLabel = new javax.swing.JLabel();
        cardNumberLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        payButton = new javax.swing.JButton();
        expirationDateFormattedField = new javax.swing.JFormattedTextField();
        totalPriceText = new javax.swing.JLabel();
        cardHolderNameFormattedField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payment - CityLink");

        terminatePaymentButton.setText("Terminate Payment");
        terminatePaymentButton.addActionListener(this::terminatePaymentButtonActionPerformed);

        paymentLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        paymentLabel.setText("Payment");

        try {
            cardNumberFormattedField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### #### #### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cardNumberFormattedField.addActionListener(this::cardNumberFormattedFieldActionPerformed);

        try {
            cvcFormattedField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cvcFormattedField.addActionListener(this::cvcFormattedFieldActionPerformed);

        cvcLabel.setText("CVC/CVV");

        expirationDateLabel.setText("Expiration Date");

        cardHolderNameLabel.setText("Name of the Card Holder");

        cardNumberLabel.setText("Card Number");

        payButton.setText("Pay");
        payButton.addActionListener(this::payButtonActionPerformed);

        try {
            expirationDateFormattedField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        totalPriceText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalPriceText.setText("Total: ₺");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(expirationDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(cvcLabel)
                .addGap(93, 93, 93))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(cardNumberLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(paymentLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(terminatePaymentButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cardNumberFormattedField, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(totalPriceText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(expirationDateFormattedField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cvcFormattedField)
                                    .addComponent(payButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                            .addComponent(cardHolderNameFormattedField))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cardHolderNameLabel)
                        .addGap(128, 128, 128))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(paymentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(cardNumberLabel)
                .addGap(2, 2, 2)
                .addComponent(cardNumberFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cardHolderNameLabel)
                .addGap(1, 1, 1)
                .addComponent(cardHolderNameFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvcLabel)
                    .addComponent(expirationDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvcFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expirationDateFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payButton)
                    .addComponent(totalPriceText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(terminatePaymentButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void terminatePaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminatePaymentButtonActionPerformed
        // TODO add your handling code here:
        int answer = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to terminate the payment process?",
            "Terminate Payment",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE);

            if (answer == javax.swing.JOptionPane.YES_OPTION) {
                if (purchaseType.equals("Single Ride")) { 
                    BuyTickets buyTicketsMenu = new BuyTickets();
                    buyTicketsMenu.setVisible(true);
                    this.setVisible(false);
            }
                else {
                    BuySubscriptions buySubscriptionsMenu = new BuySubscriptions();
                    buySubscriptionsMenu.setVisible(true);
                    this.setVisible(false);
                }
        }
    }//GEN-LAST:event_terminatePaymentButtonActionPerformed

    private void cvcFormattedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvcFormattedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvcFormattedFieldActionPerformed

    private void cardNumberFormattedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberFormattedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumberFormattedFieldActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        // TODO add your handling code here:
        String cardNumber = cardNumberFormattedField.getText();
        String cardHolderName = cardHolderNameFormattedField.getText();
        String expirationDate = expirationDateFormattedField.getText();
        String cvc = cvcFormattedField.getText();

        if (cardNumber == null || cardNumber.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a card number.");
        } 
        
        else if (cardHolderName == null || cardHolderName.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a card holder name.");
        } 
        else if (cardHolderName.trim().length() < 2 || cardHolderName.trim().length() > 50) {
            javax.swing.JOptionPane.showMessageDialog(this, "Card holder name should be minimum 2, maximum 50 characters.");
        } 
        else if (!cardHolderName.matches("^[\\p{L} ]+$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Card holder name can only have letters and spaces.");
        }
        else{
            LocalDateTime dateOfProcess = LocalDateTime.now();
            String fileName = null;
            String ticketRecord = null;
            String paymentRecord = null;
            LocalDateTime now = LocalDateTime.now();
            LocalDateTime startDate;
            LocalDateTime endDate = null;
            
            if (purchaseType.equals("Single Ride")) {
                ticketRecord = userID + ";" + vehicleType + ";" + lineName + ";" + passengerType;
                paymentRecord = dateOfProcess + ";" + cardNumber + ";" + totalPrice + ";" + vehicleType + ";" + lineName + ";" + passengerType + ";" + userID + ";" + purchaseType + ";" + amount;
                fileName = "tickets.txt";
            }
            else {
                startDate = now;
                fileName = "subscriptions.txt";
                amount = 1;
                
                if (purchaseType.equals("Daily Pass")) {
                    endDate = now.plusDays(1);
                }
                else if (purchaseType.equals("Weekly Pass")) {
                    endDate = now.plusWeeks(1);
                }
                else if (purchaseType.equals("Monthly Pass")) {
                    endDate = now.plusMonths(1);
                }
                
                ticketRecord = userID + ";" + purchaseType + ";" + passengerType + ";" + startDate + ";" + endDate;
                paymentRecord = dateOfProcess + ";" + cardNumber + ";" + totalPrice + ";" + userID + ";" + purchaseType + ";" + passengerType;
        }
            if (paymentRecord != null){
                try (BufferedWriter writer = new BufferedWriter(new FileWriter("transactionlog.txt", true))) {
                    writer.write(paymentRecord);
                    writer.newLine();

                } catch (IOException e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "File Error: " + e.getMessage());
                }
            }
            
            if (fileName != null && ticketRecord != null) {
                try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileName, true))) {
                    for (int i = 0; i < amount; i++) {
                        writer.write(ticketRecord);
                        writer.newLine();
                    }

                    JOptionPane processingPane = new JOptionPane("Processing your payment, please wait...", JOptionPane.INFORMATION_MESSAGE, JOptionPane.DEFAULT_OPTION, null, new Object[]{}, null);
                    JDialog processingDialog = processingPane.createDialog(this, "Payment in Process");

                    javax.swing.Timer processingTimer = new javax.swing.Timer(5000, e -> {
                        processingDialog.dispose();

                    });
                    processingTimer.setRepeats(false);
                    processingTimer.start();
                    processingDialog.setVisible(true);


                    JOptionPane successPane = new JOptionPane("Payment successful!\nRedirecting to Passenger Menu page...", JOptionPane.INFORMATION_MESSAGE, JOptionPane.DEFAULT_OPTION, null, new Object[]{}, null);
                    JDialog successDialog = successPane.createDialog(this, "Payment Successful");

                    javax.swing.Timer successTimer = new javax.swing.Timer(3000, e -> {
                        successDialog.dispose();
                        PassengerMenu passengerMenu = new PassengerMenu();
                        passengerMenu.setVisible(true);
                        this.setVisible(false);
                    });
                    successTimer.setRepeats(false);
                    successTimer.start();
                    successDialog.setVisible(true);

                } catch (IOException e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "File Error: " + e.getMessage());

                }
            }
        }
    
    
        
        
       

        

    }//GEN-LAST:event_payButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PaymentPage(0.0, "11111111111", 1, "Test Vehicle", "Test Line", "Adult", "SingleType").setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField cardHolderNameFormattedField;
    private javax.swing.JLabel cardHolderNameLabel;
    private javax.swing.JFormattedTextField cardNumberFormattedField;
    private javax.swing.JLabel cardNumberLabel;
    private javax.swing.JFormattedTextField cvcFormattedField;
    private javax.swing.JLabel cvcLabel;
    private javax.swing.JFormattedTextField expirationDateFormattedField;
    private javax.swing.JLabel expirationDateLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton payButton;
    private javax.swing.JLabel paymentLabel;
    private javax.swing.JButton terminatePaymentButton;
    private javax.swing.JLabel totalPriceText;
    // End of variables declaration//GEN-END:variables
}
