/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package citylink;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;


/**
 *
 * @author burak
 */
public class RemoveExistingRoutes extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RemoveExistingRoutes.class.getName());
    VehicleDropdownManager manager = new VehicleDropdownManager();

    /**
     * Creates new form RemoveExistingRoutes
     */
    public RemoveExistingRoutes() {
        initComponents();
        
        vehicleSelectComboBox.setModel(manager.getDropdownModel("routes.txt"));
        
        if (vehicleSelectComboBox.getSelectedItem() != null) {
            String initialVehicle = vehicleSelectComboBox.getSelectedItem().toString();
            lineSelectComboBox.setModel(manager.getLineDropdownModel("routes.txt", initialVehicle));
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addNewRouteLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        removeAllExistingRoutesButton = new javax.swing.JButton();
        vehicleSelectComboBox = new javax.swing.JComboBox<>();
        lineSelectComboBox = new javax.swing.JComboBox<>();
        lineLabel = new javax.swing.JLabel();
        vehicleLabel = new javax.swing.JLabel();
        removeSelectedLineButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remove Existing Routes - CityLink");

        addNewRouteLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addNewRouteLabel.setText("Remove Existing Routes");

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        removeAllExistingRoutesButton.setText("Remove All Existing Routes");
        removeAllExistingRoutesButton.addActionListener(this::removeAllExistingRoutesButtonActionPerformed);

        vehicleSelectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bus", "Metro", "Tram", "Ferry" }));
        vehicleSelectComboBox.addActionListener(this::vehicleSelectComboBoxActionPerformed);

        lineSelectComboBox.setToolTipText("Select the line you want to remove.");
        lineSelectComboBox.setName(""); // NOI18N
        lineSelectComboBox.addActionListener(this::lineSelectComboBoxActionPerformed);

        lineLabel.setText("Line");

        vehicleLabel.setText("Vehicle");

        removeSelectedLineButton.setText("Remove Selected Route");
        removeSelectedLineButton.addActionListener(this::removeSelectedLineButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(vehicleSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lineSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(vehicleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lineLabel)
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(72, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addNewRouteLabel)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(removeAllExistingRoutesButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(removeSelectedLineButton)
                                .addGap(8, 8, 8)))
                        .addGap(103, 103, 103))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(addNewRouteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleLabel)
                    .addComponent(lineLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lineSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(removeSelectedLineButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(removeAllExistingRoutesButton)
                .addGap(7, 7, 7)
                .addComponent(backButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        AdminMenu adminMenu = new AdminMenu();
        adminMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void removeAllExistingRoutesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAllExistingRoutesButtonActionPerformed
        // TODO add your handling code here:
        if (vehicleSelectComboBox.getSelectedItem() == null || lineSelectComboBox.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "There is no existing route available to be removed.");
            return;
        }
        int answer = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to remove all existing routes?\nThis action cannot be undone.",
                "Remove All Existing Routes",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);

        if (answer == javax.swing.JOptionPane.YES_OPTION) {
            
            try (BufferedWriter writer = new BufferedWriter(new FileWriter("routes.txt", false))) {
                writer.write("");
                writer.newLine();
                javax.swing.JOptionPane.showMessageDialog(this, "All existing routes have been removed successfully.");
                vehicleSelectComboBox.setModel(manager.getDropdownModel("routes.txt"));
                lineSelectComboBox.setModel(new DefaultComboBoxModel<>());

            } catch (IOException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "File Error: " + e.getMessage());

            }

        }


    }//GEN-LAST:event_removeAllExistingRoutesButtonActionPerformed

    private void removeSelectedLineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSelectedLineButtonActionPerformed
        // TODO add your handling code here: 
        if (vehicleSelectComboBox.getSelectedItem() == null || lineSelectComboBox.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "There is no existing route available to be removed.");
            return;
        }
        
        String vehicleType = vehicleSelectComboBox.getSelectedItem().toString();
        String lineName = lineSelectComboBox.getSelectedItem().toString();
        System.out.println(vehicleType + " " + lineName);
        
        int answer = JOptionPane.showConfirmDialog(this, "Are you sure to remove " + vehicleType + " line named " + lineName + "?\nThis action cannot be undone.", "Remove an Existing Route" ,JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if (answer == JOptionPane.YES_OPTION) {
            ArrayList<String> remainingRoutes = new ArrayList<>();
            boolean isRemoved = false;
            try (BufferedReader reader = new BufferedReader(new FileReader("routes.txt"))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String[] parts = line.split(";");

                    if (parts.length >= 2 && parts[0].equals(vehicleType) && parts[1].equals(lineName)) {
                        isRemoved = true;
                    } else {
                        remainingRoutes.add(line);
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error occured in reading file: " + e.getMessage());
            }
            
            if (isRemoved) {
                try (BufferedWriter writer = new BufferedWriter(new FileWriter("routes.txt", false))) {
                    
                    for (int i = 0; i < remainingRoutes.size(); i++) {
                        writer.write(remainingRoutes.get(i));
                        writer.newLine();
                    } 

                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "Error occured in writing to file: " + e.getMessage());
                }
                JOptionPane.showMessageDialog(this, vehicleType + " route " + lineName + " has been removed successfully.");

                vehicleSelectComboBox.setModel(manager.getDropdownModel("routes.txt"));
                if (vehicleSelectComboBox.getSelectedItem() != null) {
                    lineSelectComboBox.setModel(manager.getLineDropdownModel("routes.txt", vehicleSelectComboBox.getSelectedItem().toString()));
                } else {
                    lineSelectComboBox.setModel(new DefaultComboBoxModel<>());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Could not find the selected route in the file.");
            }
        }
        


    
    }//GEN-LAST:event_removeSelectedLineButtonActionPerformed

    private void vehicleSelectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleSelectComboBoxActionPerformed
        // TODO add your handling code here:
        String selectedVehicle = vehicleSelectComboBox.getSelectedItem().toString();
        DefaultComboBoxModel<String> lineModel = manager.getLineDropdownModel("routes.txt", selectedVehicle);
        lineSelectComboBox.setModel(lineModel);
    }//GEN-LAST:event_vehicleSelectComboBoxActionPerformed

    private void lineSelectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineSelectComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lineSelectComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RemoveExistingRoutes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addNewRouteLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lineLabel;
    private javax.swing.JComboBox<String> lineSelectComboBox;
    private javax.swing.JButton removeAllExistingRoutesButton;
    private javax.swing.JButton removeSelectedLineButton;
    private javax.swing.JLabel vehicleLabel;
    private javax.swing.JComboBox<String> vehicleSelectComboBox;
    // End of variables declaration//GEN-END:variables
}
