/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package citylink;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author burak
 */
public class RemoveServiceAlerts extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RemoveServiceAlerts.class.getName());
    VehicleDropdownManager manager = new VehicleDropdownManager();

    /**
     * Creates new form RemoveServiceAlerts
     */
    public RemoveServiceAlerts() {
        initComponents();
        
        vehicleSelectComboBox.setModel(manager.getDropdownModel("routes.txt"));
        
        if (vehicleSelectComboBox.getSelectedItem() != null) {
            String initialVehicle = vehicleSelectComboBox.getSelectedItem().toString();
            lineSelectComboBox.setModel(manager.getLineDropdownModel("routes.txt", initialVehicle));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RemoveServiceAlertsLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        backButton = new javax.swing.JButton();
        removeAllServiceAlertsButton = new javax.swing.JButton();
        vehicleSelectComboBox = new javax.swing.JComboBox<>();
        lineSelectComboBox = new javax.swing.JComboBox<>();
        lineLabel = new javax.swing.JLabel();
        vehicleLabel = new javax.swing.JLabel();
        removeSelectedServiceAlertButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RemoveServiceAlertsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RemoveServiceAlertsLabel.setText("Remove Service Alerts");

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        removeAllServiceAlertsButton.setText("Remove All Service Alerts");
        removeAllServiceAlertsButton.addActionListener(this::removeAllServiceAlertsButtonActionPerformed);

        vehicleSelectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bus", "Metro", "Tram", "Ferry" }));
        vehicleSelectComboBox.addActionListener(this::vehicleSelectComboBoxActionPerformed);

        lineLabel.setText("Line");

        vehicleLabel.setText("Vehicle");

        removeSelectedServiceAlertButton.setText("Remove Selected Service Alert");
        removeSelectedServiceAlertButton.addActionListener(this::removeSelectedServiceAlertButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 102, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(RemoveServiceAlertsLabel)
                                .addGap(105, 105, 105))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(vehicleSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lineSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(vehicleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lineLabel)
                .addGap(81, 81, 81))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(removeAllServiceAlertsButton)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(removeSelectedServiceAlertButton)
                        .addGap(97, 97, 97))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(RemoveServiceAlertsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lineLabel))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lineSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(removeSelectedServiceAlertButton)
                .addGap(31, 31, 31)
                .addComponent(removeAllServiceAlertsButton)
                .addGap(8, 8, 8)
                .addComponent(backButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        AdminMenu adminMenu = new AdminMenu();
        adminMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void removeAllServiceAlertsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAllServiceAlertsButtonActionPerformed
        // TODO add your handling code here:
        int answer = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to remove all existing service alerts?\nThis action cannot be undone.",
                "Remove All Existing Service Alerts",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);

        if (answer == javax.swing.JOptionPane.YES_OPTION) {
            
            try (BufferedWriter writer = new BufferedWriter(new FileWriter("servicealerts.txt", false))) {
                writer.write("");
                writer.newLine();
                javax.swing.JOptionPane.showMessageDialog(this, "All existing service alerts have been removed successfully.");

            } catch (IOException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "File Error: " + e.getMessage());

            }

        }
    }//GEN-LAST:event_removeAllServiceAlertsButtonActionPerformed

    private void vehicleSelectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleSelectComboBoxActionPerformed
        // TODO add your handling code here:
        String selectedVehicle = vehicleSelectComboBox.getSelectedItem().toString();
        DefaultComboBoxModel<String> lineModel = manager.getLineDropdownModel("routes.txt", selectedVehicle);
        lineSelectComboBox.setModel(lineModel);
    }//GEN-LAST:event_vehicleSelectComboBoxActionPerformed

    private void removeSelectedServiceAlertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSelectedServiceAlertButtonActionPerformed
        // TODO add your handling code here:
        if (vehicleSelectComboBox.getSelectedItem() == null || lineSelectComboBox.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "There is no existing route available.\nPlease use Remove All fuction instead.");
            return;
        }
        
        String vehicleType = vehicleSelectComboBox.getSelectedItem().toString();
        String lineName = lineSelectComboBox.getSelectedItem().toString();
        System.out.println(vehicleType + " " + lineName);
        
        int answer = JOptionPane.showConfirmDialog(this, "Are you sure to remove all service alerts associated with " + vehicleType + " line named " + lineName + "?\nThis action cannot be undone.", "Remove an Existing Service Alert" ,JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if (answer == JOptionPane.YES_OPTION) {
            ArrayList<String> remainingServiceAlerts = new ArrayList<>();
            boolean isRemoved = false;
            try (BufferedReader reader = new BufferedReader(new FileReader("servicealerts.txt"))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String[] parts = line.split(";");

                    if (parts.length >= 2 && parts[0].equals(vehicleType) && parts[1].equals(lineName)) {
                        isRemoved = true;
                    } else {
                        remainingServiceAlerts.add(line);
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error occured in reading file: " + e.getMessage());
            }
            
            if (isRemoved) {
                try (BufferedWriter writer = new BufferedWriter(new FileWriter("servicealerts.txt", false))) {
                    
                    for (int i = 0; i < remainingServiceAlerts.size(); i++) {
                        writer.write(remainingServiceAlerts.get(i));
                        writer.newLine();
                    } 

                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "Error occured in writing to file: " + e.getMessage());
                }
                JOptionPane.showMessageDialog(this, "The service alerts associated with " + vehicleType + " route " + lineName + " have been removed successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Could not find any alert associated with the selected route in the file.");
            }
        }
    }//GEN-LAST:event_removeSelectedServiceAlertButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RemoveServiceAlerts().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RemoveServiceAlertsLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lineLabel;
    private javax.swing.JComboBox<String> lineSelectComboBox;
    private javax.swing.JButton removeAllServiceAlertsButton;
    private javax.swing.JButton removeSelectedServiceAlertButton;
    private javax.swing.JLabel vehicleLabel;
    private javax.swing.JComboBox<String> vehicleSelectComboBox;
    // End of variables declaration//GEN-END:variables
}
