/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package citylink;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author burak
 */
public class RemoveScheduleInfo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RemoveScheduleInfo.class.getName());
    VehicleDropdownManager manager = new VehicleDropdownManager();

    /**
     * Creates new form RemoveScheduleInfo
     */
    public RemoveScheduleInfo() {
        initComponents();
        
        vehicleSelectorComboBox.setModel(manager.getDropdownModel("routes.txt"));
        
        if (vehicleSelectorComboBox.getSelectedItem() != null) {
            String initialVehicle = vehicleSelectorComboBox.getSelectedItem().toString();
            lineSelectorComboBox.setModel(manager.getLineDropdownModel("routes.txt", initialVehicle));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeScheduleInfoLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        backButton = new javax.swing.JButton();
        vehicleSelectorComboBox = new javax.swing.JComboBox<>();
        lineSelectorComboBox = new javax.swing.JComboBox<>();
        vehicleLabel = new javax.swing.JLabel();
        lineLabel = new javax.swing.JLabel();
        removeSelectedScheduleInfoButton = new javax.swing.JButton();
        removeAllScheduleInfoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remove Schedule Info - CityLink");

        removeScheduleInfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        removeScheduleInfoLabel.setText("Remove Schedule Info");

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        vehicleSelectorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bus", "Metro", "Tram", "Ferry" }));
        vehicleSelectorComboBox.addActionListener(this::vehicleSelectorComboBoxActionPerformed);

        lineSelectorComboBox.addActionListener(this::lineSelectorComboBoxActionPerformed);

        vehicleLabel.setText("Vehicle");

        lineLabel.setText("Line");

        removeSelectedScheduleInfoButton.setText("Remove Selected Schedule Info");
        removeSelectedScheduleInfoButton.addActionListener(this::removeSelectedScheduleInfoButtonActionPerformed);

        removeAllScheduleInfoButton.setText("Remove All Schedule Info");
        removeAllScheduleInfoButton.addActionListener(this::removeAllScheduleInfoButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(vehicleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lineLabel)
                .addGap(91, 91, 91))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(vehicleSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lineSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(removeScheduleInfoLabel)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(removeAllScheduleInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(removeSelectedScheduleInfoButton)
                        .addGap(90, 90, 90))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(removeScheduleInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleLabel)
                    .addComponent(lineLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lineSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(removeSelectedScheduleInfoButton)
                .addGap(26, 26, 26)
                .addComponent(removeAllScheduleInfoButton)
                .addGap(16, 16, 16)
                .addComponent(backButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        AdminMenu adminMenu = new AdminMenu();
        adminMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void vehicleSelectorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleSelectorComboBoxActionPerformed
        // TODO add your handling code here:
        String selectedVehicle = vehicleSelectorComboBox.getSelectedItem().toString();

        DefaultComboBoxModel<String> lineModel = manager.getLineDropdownModel("routes.txt", selectedVehicle);

        lineSelectorComboBox.setModel(lineModel);
    }//GEN-LAST:event_vehicleSelectorComboBoxActionPerformed

    private void lineSelectorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineSelectorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lineSelectorComboBoxActionPerformed

    private void removeAllScheduleInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAllScheduleInfoButtonActionPerformed
        // TODO add your handling code here:
        int answer = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to remove all existing schedule info?\nThis action cannot be undone.",
                "Remove All Existing Schedule Info",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);

        if (answer == javax.swing.JOptionPane.YES_OPTION) {
            
            try (BufferedWriter writer = new BufferedWriter(new FileWriter("schedules.txt", false))) {
                writer.write("");
                writer.newLine();
                javax.swing.JOptionPane.showMessageDialog(this, "All existing schedule info have been removed successfully.");

            } catch (IOException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "File Error: " + e.getMessage());

            }

        }
    }//GEN-LAST:event_removeAllScheduleInfoButtonActionPerformed

    private void removeSelectedScheduleInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSelectedScheduleInfoButtonActionPerformed
        // TODO add your handling code here:
        //Check route availability
        if (vehicleSelectorComboBox.getSelectedItem() == null || lineSelectorComboBox.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "There is no existing route available.\nPlease use Remove All fuction instead.");
            return;
        }
        
        String vehicleType = vehicleSelectorComboBox.getSelectedItem().toString();
        String lineName = lineSelectorComboBox.getSelectedItem().toString();
        System.out.println(vehicleType + " " + lineName);
        
        int answer = JOptionPane.showConfirmDialog(this, "Are you sure to remove all schedule info associated with " + vehicleType + " line named " + lineName + "?\nThis action cannot be undone.", "Remove an Existing Schedule Info" ,JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if (answer == JOptionPane.YES_OPTION) {
            ArrayList<String> remainingServiceAlerts = new ArrayList<>();
            boolean isRemoved = false;
            try (BufferedReader reader = new BufferedReader(new FileReader("schedules.txt"))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String[] parts = line.split(";");

                    if (parts.length >= 2 && parts[0].equals(vehicleType) && parts[1].equals(lineName)) {
                        isRemoved = true;
                    } else {
                        remainingServiceAlerts.add(line);
                    }
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error occured in reading file: " + e.getMessage());
            }
            
            if (isRemoved) {
                try (BufferedWriter writer = new BufferedWriter(new FileWriter("schedules.txt", false))) {
                    
                    for (int i = 0; i < remainingServiceAlerts.size(); i++) {
                        writer.write(remainingServiceAlerts.get(i));
                        writer.newLine();
                    } 

                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "Error occured in writing to file: " + e.getMessage());
                }
                JOptionPane.showMessageDialog(this, "The schedule info associated with " + vehicleType + " route " + lineName + " have been removed successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Could not find any schedule info associated with the selected route in the file.");
            }
        }
    }//GEN-LAST:event_removeSelectedScheduleInfoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RemoveScheduleInfo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lineLabel;
    private javax.swing.JComboBox<String> lineSelectorComboBox;
    private javax.swing.JButton removeAllScheduleInfoButton;
    private javax.swing.JLabel removeScheduleInfoLabel;
    private javax.swing.JButton removeSelectedScheduleInfoButton;
    private javax.swing.JLabel vehicleLabel;
    private javax.swing.JComboBox<String> vehicleSelectorComboBox;
    // End of variables declaration//GEN-END:variables
}
