/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package citylink;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author burak
 */
public class ViewServiceAlerts extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewServiceAlerts.class.getName());

    /**
     * Creates new form ViewServiceAlerts
     */
    public ViewServiceAlerts() {
        initComponents();
        
        loadServiceAlerts();
    }
    
    public void loadServiceAlerts() {
        serviceAlertsTextArea.setText("");
        try (BufferedReader reader = new BufferedReader(new FileReader("servicealerts.txt"))) {
            String line;
            StringBuilder formattedText = new StringBuilder(); 

        while ((line = reader.readLine()) != null) {
            String[] parts = line.split(";"); 
            if (parts.length >= 5) {
                String vehicleType = parts[0];
                String lineName = parts[1];
                String startDate = parts[2];
                String endDate = parts[3];
                String alertMessage = parts[4]; 
                
                String displayLine; 
                displayLine = String.format("Vehicle: " + vehicleType + "\nLine: " + lineName + "\nStart Date: " + startDate + "\nEnd Date: " + endDate + "\nAlert Message: " + alertMessage + "\n \n");
                                                    
                formattedText.append(displayLine);
            } else {
                formattedText.append(line).append("");
            }
        }
        
        if (formattedText.toString().isBlank()) {
            serviceAlertsTextArea.setText("There is no service alert right now.");
        }
        else {
        serviceAlertsTextArea.setText(formattedText.toString());
        }

    } catch (IOException e) {
        System.out.println("No service alert found.");
    }
            

        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        viewServiceAlertsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        serviceAlertsTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Service Alerts - CityLink");

        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        viewServiceAlertsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewServiceAlertsLabel.setText("View Service Alerts");

        serviceAlertsTextArea.setEditable(false);
        serviceAlertsTextArea.setColumns(20);
        serviceAlertsTextArea.setLineWrap(true);
        serviceAlertsTextArea.setRows(5);
        serviceAlertsTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(serviceAlertsTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewServiceAlertsLabel)
                        .addGap(116, 116, 116))))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(viewServiceAlertsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        PassengerMenu passengerMenu = new PassengerMenu();
        passengerMenu.setVisible(true);
        this.setVisible(false);
        //if time has passed, delete that alert
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewServiceAlerts().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea serviceAlertsTextArea;
    private javax.swing.JLabel viewServiceAlertsLabel;
    // End of variables declaration//GEN-END:variables
}
